# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Helper function to set up covariance matrix
#' @param N number of years
#' @param lambda vector of lambda values (one for each box)
#' @param weights vector of weights values (one for each box)
#' @param deltat time step in years (usually 1)
#' @param noise_factor constant scaling factor for AR(1) noise,
#' related to (see sx_from_sd and sd_from_sx)
#' @param o SD of white noise
#' @export
setup_sigma <- function(N, lambda, weights, deltat, noise_factor, o) {
    .Call(`_ClimBayes_setup_sigma`, N, lambda, weights, deltat, noise_factor, o)
}

#' Helper function to solve the ODE
#' @param n_years number of years considered
#' @param lambda vector for lambda, each entry corresponding to one box
#' @param weights vector of weights values, one for each box; should sum up to 1
#' @param forc_vals vector of forcing values (yearly data)
#' @param F0 initial forcing value
#' @return vector of solution values,
#' not scaled be heat capacity yet
#' @export
ode_helper <- function(n_years, lambda, weights, forc_vals, F0) {
    .Call(`_ClimBayes_ode_helper`, n_years, lambda, weights, forc_vals, F0)
}

#' Simple C++ code for matrix-vector multiplication
#' @param m matrix
#' @param v vector
#' @return matrix product (but in a fast way)
#' @export
my_mm <- function(m, v) {
    .Call(`_ClimBayes_my_mm`, m, v)
}

