# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
timesTwo <- function(x) {
    .Call(`_ClimBayes_timesTwo`, x)
}

#' test
#'
#' test
#'
#' @param N ...
#' @export
setup_sigma <- function(N, lambda, weights, deltat, noise_factor, o) {
    .Call(`_ClimBayes_setup_sigma`, N, lambda, weights, deltat, noise_factor, o)
}

#' helper function to solve the ODE
#' @param n_years number of years considered
#' @param lambda vector for lambda, each entry corresponding to one box
#' @param weights vector of weights values, one for each box; should sum up to 1
#' @param forc_vals vector of forcing values (yearly data)
#' @param F0 initial forcing value
#' @return vector of solution values,
#' not scaled be heat capacity yet
#' @export
ode_helper <- function(n_years, lambda, weights, forc_vals, F0) {
    .Call(`_ClimBayes_ode_helper`, n_years, lambda, weights, forc_vals, F0)
}

#'
#' @param m ...
#' @export
my_mm <- function(m, v) {
    .Call(`_ClimBayes_my_mm`, m, v)
}

